Repository openshift/machine-api-provider-gcp, pull requests merged in 2022-12, with the labels that each got.

#21 OCPBUGS-1557: refactor restartPolicyToBool function
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#24 OCPBUGS-860: Set sync period for Machine controller
  cmd/manager/main.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#28 [release-4.12] OCPBUGS-4504: refactor restartPolicyToBool function
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
Labels: lgtm, approved, backport-risk-assessed, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#22 OCPBUGS-3904: Register unknown instance groups
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Labels: lgtm, qe-approved, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#35 Update OWNERS
  OWNERS
Labels: lgtm, approved

#30 [release-4.11] OCPBUGS-4579: refactor restartPolicyToBool function
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
Labels: lgtm, cherry-pick-approved, approved, backport-risk-assessed, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug
