Repository openshift/machine-api-provider-gcp, pull requests merged in 2023-10, with the labels that each got.

#61 OCPBUGS-20267: update bad url endpoint termination handler test
  pkg/termination/termination_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#63 Update OWNERS
  OWNERS
Labels: lgtm, approved

#60 MIXEDARCH-258: Set the capacity annotation for arch-aware autoscale from zero
  pkg/cloud/gcp/actuators/machineset/controller.go
  pkg/cloud/gcp/actuators/machineset/controller_test.go
  pkg/cloud/gcp/actuators/util/gcp_machine_architecture.go
  pkg/cloud/gcp/actuators/util/gcp_machine_architecture_test.go
Labels: lgtm, approved, jira/valid-reference
